In [1]:
import pandas as pd

df = pd.read_csv('/data/oe23/fert-recon/comprehensive_pixels_dataset.csv')

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load the processed dataset
df = pd.read_csv('../../data/processed/comprehensive_pixels_dataset.csv')

print(f"Dataset shape: {df.shape}")
print(f"Memory usage: {df.memory_usage(deep=True).sum() / 1024**2:.1f} MB")
print("\nColumn names:")
print(df.columns.tolist())
df.head()

,pixel_id,year,GlobalSurfaceWater_change_abs_2000,GlobalSurfaceWater_change_norm_2000,GlobalSurfaceWater_max_extent_2000,GlobalSurfaceWater_occurrence_2000,GlobalSurfaceWater_recurrence_2000,GlobalSurfaceWater_seasonality_2000,GlobalSurfaceWater_transition_2000,chirps_mean_m01_2000,...,terraclimate_vs_mean_m03_2000.1,terraclimate_vs_mean_m04_2000.1,terraclimate_vs_mean_m05_2000.1,terraclimate_vs_mean_m06_2000.1,terraclimate_vs_mean_m07_2000.1,terraclimate_vs_mean_m08_2000.1,terraclimate_vs_mean_m09_2000.1,terraclimate_vs_mean_m10_2000.1,terraclimate_vs_mean_m11_2000.1,terraclimate_vs_mean_m12_2000.1
0,0,2000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,2000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,2000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,2000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,2000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
608251,38011,2015,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2947.0,2838.0,2708.0,2504.0,2345.0,2039.0,1824.0,0.0,0.0,0.0
608252,38012,2015,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2946.0,2841.0,2716.0,2508.0,2345.0,2038.0,1824.0,0.0,0.0,0.0
608253,38013,2015,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2951.0,2839.0,2711.0,2506.0,2345.0,2037.0,1822.0,0.0,0.0,0.0
608254,38014,2015,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2949.0,2842.0,2705.0,2509.0,2342.0,2042.0,1826.0,0.0,0.0,0.0
608255,38015,2015,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2947.0,2836.0,2708.0,2511.0,2340.0,2041.0,1831.0,0.0,0.0,0.0